# Generated by Django 5.2.7 on 2025-10-19 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REPORTED", "Reported"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="REPORTED",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FACILITIES", "Facilities"),
                            ("IT", "IT/Tech"),
                            ("SAFETY", "Safety"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        choices=[
                            (
                                "SCIENCE_CENTER",
                                "Dorothy Westerman Herrmann Science Center",
                            ),
                            ("LANDRUM", "Landrum Academic Center"),
                            ("LIBRARY", "W. Frank Steely Library"),
                            ("FINE_ARTS", "Fine Arts Center"),
                            ("BUSINESS_ACADEMIC", "Business Academic Center"),
                            ("MEP_CENTER", "Math-Education-Psychology Center"),
                            ("LUCAS_ADMIN", "Lucas Administrative Center"),
                            (
                                "UNIVERSITY_CENTER",
                                "University Center and Welcome Center",
                            ),
                            (
                                "STUDENT_UNION",
                                "James C. and Rachel M. Votruba Student Union",
                            ),
                            ("NUNN_HALL", "Louie B. Nunn Hall"),
                            ("HEALTH_INNOVATION", "Health Innovation Center"),
                            ("FOUNDERS_HALL", "Founders Hall"),
                            ("GRIFFIN_HALL", "Griffin Hall"),
                            (
                                "REC_CENTER",
                                "Campus Recreation Center & Albright Health Center",
                            ),
                            ("OTHER", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "specific_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Room 201, second floor men's restroom",
                        max_length=255,
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="issue_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VOte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="tracker.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "issue")},
            },
        ),
    ]
